/* Essai indépendant. Le TBI conserve l'état ; le téléphone envoie des commandes datées. */
'use strict';
window.esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.NB_CARTES=32;
window.reponseCarte=(m,rotation=0)=>{const c=m.corners,cx=c.reduce((s,p)=>s+p.x,0)/4,cy=c.reduce((s,p)=>s+p.y,0)/4,x=(c[0].x+c[1].x)/2-cx,y=(c[0].y+c[1].y)/2-cy,a=rotation*Math.PI/180,tx=x*Math.cos(a)+y*Math.sin(a),ty=y*Math.cos(a)-x*Math.sin(a);return Math.abs(ty)>=Math.abs(tx)?(ty<0?'A':'C'):(tx<0?'B':'D');};
window.Sorciers=(()=>{
  const C=SorcierCore,B=SORCIERS_BANQUE,KEY='sorciers-essai:etat:v1',MIRROR='sorciers-essai:copie:v1';
  const H=[{nom:'Gryffondor',trait:'Le courage',couleur:'#bb4742'},{nom:'Serdaigle',trait:'La curiosité',couleur:'#337eaf'},{nom:'Poufsouffle',trait:'L’entraide',couleur:'#ae7816'},{nom:'Serpentard',trait:'La détermination',couleur:'#358064'}];
  const tel=new URLSearchParams(location.search).get('role')==='tel';
  let S=C.neuf(),view='home',shared='home',room=null,pairs=[],lastState=0,authority=null,cameraMounted=false,lastQ=null,podiumTotal=false,ready=false,corrupt=false,lastShared=null;
  S.notions=B.notions.filter(n=>n.vue).map(n=>n.id);
  let pending=new Map(),handled=new Map(),incomingFile=null,scanPending={},scanTimer=null;
  const $=s=>document.querySelector(s),E=window.esc,connected=()=>tel?!!authority&&pairs.some(p=>p.peer===authority)&&Date.now()-lastState<22000:true;
  const crest=h=>`<span class="crest" style="--h:${h}" aria-hidden="true"></span>`;
  const house=h=>H[h]?.nom||'À répartir';
  const can=()=>!corrupt&&(!tel||connected());
  function notice(s,bad=false){const el=$('#notice');el.textContent=s;el.hidden=!s;el.classList.toggle('error',bad);}
  function save(){try{localStorage.setItem(tel?MIRROR:KEY,JSON.stringify(S));return true;}catch(e){notice('La sauvegarde sur cet appareil est indisponible. Télécharge une copie dans Sauvegarde avant de fermer.',true);return false;}}
  function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([corrupt?localStorage.getItem(KEY):JSON.stringify({format:'sorciers-essai/sauvegarde',date:new Date().toISOString(),etat:S},null,2)],{type:'application/json'}));a.download='secrets-poudlard-'+C.jour()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
  function broadcast(){if(room&&!tel)room.emit('pv',{app:'sorciers-v1',etat:S,view:shared});}
  function setView(v){view=v;draw();}
  function apply(cmd){
    if(corrupt)throw Error('Restaure une sauvegarde valide sur l’ordinateur pour continuer.');
    const p=cmd.p||{},t=S.session;let changed=true;
    switch(cmd.type){
      case 'start':C.demarre(S,B.questions);view=shared='quiz';break;
      case 'answer':changed=C.repond(S,p.qid,p.reponses,true);break;
      case 'scan':changed=C.repond(S,p.qid,p.reponses,false);break;
      case 'reveal':changed=C.valide(S,p.qid);break;
      case 'next':changed=C.suivant(S,p.qid);break;
      case 'podium':if(!C.fin(S))return false;view=shared='podium';break;
      case 'home':view=shared='home';break;
      case 'roster':{const incoming=C.listeEleves(p.eleves);S.eleves=incoming;S.nom=String(p.nom||S.nom).trim().slice(0,60)||'Ma classe';break;}
      case 'house':{const e=S.eleves.find(e=>e.n===+p.n);if(!e||!(p.h===null||C.maison(p.h)))return false;e.maison=p.h;break;}
      case 'absent':{if(!S.eleves.some(e=>e.n===+p.n))return false;if(S.absents.jour!==C.jour())S.absents={jour:C.jour(),n:[]};S.absents.n=S.absents.n.filter(n=>n!==+p.n);if(p.absent)S.absents.n.push(+p.n);break;}
      case 'split':{const a=S.eleves.filter(e=>e.actif&&e.maison===null);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}const counts=H.map((_,h)=>S.eleves.filter(e=>e.actif&&e.maison===h).length);a.forEach(e=>{const h=counts.indexOf(Math.min(...counts));e.maison=h;counts[h]++;});break;}
      case 'notion':{if(!B.notions.some(n=>n.id===p.id))return false;const a=new Set(S.notions===null?B.notions.map(n=>n.id):S.notions);p.enabled?a.add(p.id):a.delete(p.id);S.notions=[...a];break;}
      case 'import':C.importer(S,p.data);view='students';break;
      case 'seal':if(!C.fin(S))throw Error('Termine un rituel pour ouvrir le secret de la serre.');S.sceau=true;if(!S.vendredis.includes(C.jour()))S.vendredis.push(C.jour());view=shared='secret';break;
      default:return false;
    }
    if(changed){S.rev++;save();draw();broadcast();}return changed;
  }
  function send(type,p={}){if(!can()){notice(tel?'Le téléphone attend l’écran de la classe. Garde cet écran ouvert et vérifie la connexion.':'Restaure une sauvegarde valide pour continuer.',true);return;}
    const cmd={app:'sorciers-v1',id:C.uid(),at:Date.now(),type,p};
    if(tel){cmd.owner=S.id;pending.set(cmd.id,{cmd,tries:0});room.emit('cmd',cmd);if(['start','podium','home','seal'].includes(type))view=type==='start'?'quiz':type==='seal'?'secret':type;draw();}
    else try{apply(cmd);}catch(e){notice(e.message,true);}
  }
  function status(){const el=$('#link-status');el.textContent=tel?(connected()?'Écran relié':'En attente de l’écran'):(pairs.some(p=>p.presence?.role==='sorcier-tel')?'Téléphone relié':'Écran de la classe · '+(room?.connected()?'prêt à relier':'mode local'));el.classList.toggle('linked',tel?connected():pairs.some(p=>p.presence?.role==='sorcier-tel'));document.querySelectorAll('[data-write]').forEach(b=>b.disabled=!can());}
  async function connect(){
    try{
      localStorage.setItem('sorciers-essai-mode',tel?'tel':'tbi');
      const code=new URLSearchParams(location.hash.slice(1)).get('lien');if(code){if(!Autonome.Liaison.normalise(code))throw Error('Le code de liaison est invalide.');await Autonome.Liaison.fixe(code);history.replaceState(null,'',location.pathname+location.search);}
      room=await Autonome.Liaison.ouvre();
      if(!room){view='connection';draw();status();return;}
      await room.presence({role:tel?'sorcier-tel':'sorcier-tbi',app:'sorciers-v1'});
      room.onPeers(ch=>{pairs=ch.peers.filter(p=>p.presence?.app==='sorciers-v1');if(tel&&!pairs.some(p=>p.peer===authority))authority=null;status();if(!tel)broadcast();});
      room.onConnection(()=>{status();broadcast();});
      room.on('pv',m=>{if(!tel||m.isMe||m.data?.app!=='sorciers-v1')return;if(!pairs.some(p=>p.peer===m.peer&&p.presence?.role==='sorcier-tbi'))return;
        if(authority&&authority!==m.peer)return;
        try{const n=C.restore(m.data.etat);if(S.id===n.id&&n.rev<S.rev)return;authority=m.peer;lastState=Date.now();const changed=S.id!==n.id||S.rev!==n.rev||!ready,oldView=view;S=n;ready=true;save();if(lastShared!==m.data.view){view=m.data.view||'home';lastShared=m.data.view;}if(changed||view!==oldView)draw();status();}catch(e){notice('L’état envoyé par l’écran ne peut pas être lu : '+e.message,true);}});
      room.on('cmd',m=>{if(tel||m.isMe||m.data?.app!=='sorciers-v1')return;const cmd=m.data;if(!pairs.some(p=>p.peer===m.peer&&p.presence?.role==='sorcier-tel'))return;
        let error=handled.get(cmd.id);if(error===undefined){error='';if(cmd.owner!==S.id||Math.abs(Date.now()-cmd.at)>25000)error='Cette commande a expiré. Réessaie depuis le téléphone.';else try{apply(cmd);}catch(e){error=e.message;}handled.set(cmd.id,error);if(handled.size>300)handled.delete(handled.keys().next().value);}
        room.emit('ack',{app:'sorciers-v1',id:cmd.id,error});broadcast();});
      room.on('ack',m=>{if(!tel||m.isMe||m.peer!==authority||m.data?.app!=='sorciers-v1')return;pending.delete(m.data.id);if(m.data.error)notice(m.data.error,true);});
      room.on('scan',m=>{if(tel||m.isMe||m.data?.app!=='sorciers-v1'||!pairs.some(p=>p.peer===m.peer&&p.presence?.role==='sorcier-tel'))return;if(m.data.owner!==S.id)return;try{apply({type:'scan',p:m.data});}catch(e){notice(e.message,true);}});
      broadcast();if(view==='connection')draw();status();
    }catch(e){notice('La liaison n’a pas pu démarrer : '+e.message,true);status();}
  }
  function houses(points=C.total(S)){return `<div class="houses">${H.map((h,i)=>`<article class="house" style="--house:${h.couleur}">${crest(i)}<div><b>${h.nom}</b><small>${S.eleves.filter(e=>e.actif&&e.maison===i).length} élèves</small></div><strong>${points[i]}<small>points</small></strong></article>`).join('')}</div>`;}
  function heading(k,t,p=''){return `<div class="page-heading"><div class="eyebrow">${k}</div><h1>${t}</h1>${p?`<p>${p}</p>`:''}</div>`;}
  const button=(action,label,secondary=false,extra='')=>`<button class="action${secondary?' secondary':''}" data-act="${action}" data-write ${extra}>${label}</button>`;
  function home(){const active=S.session&&!C.fin(S);return `<section class="hero"><div class="hero-copy"><div class="eyebrow">Bienvenue à Poudlard</div><h1>Le château<br>compte sur vous !</h1><p>À vos baguettes ! Répondez aux défis, gagnez des points et découvrez les secrets du château.</p>${S.eleves.some(e=>e.actif)?button('start',active?'Reprendre l’aventure':'C’est parti !'):`<button class="action" data-view="students">Préparer ma classe</button>`}<span class="hero-note">6 questions · +5 points par bonne réponse</span></div></section>
      <div class="section-heading"><h2>Qui fera briller sa maison ?</h2><button class="text-button" data-view="podium">Voir le podium →</button></div>${houses()}
      <section class="chapter"><img src="assets/serre.webp" alt="Une serre enchantée abrite un petit dragon de feuilles."><div><div class="eyebrow">Premier secret · La serre oubliée</div><h2>Chut… ça bouge dans la serre !</h2><p>Chaque vendredi, les quatre maisons unissent leurs savoirs pour découvrir un secret. Toutes les maisons avancent ensemble.</p><button class="action secondary" data-view="secret">${S.sceau?'Retourner dans la serre':'Découvrir l’aventure'}</button></div></section>
      <div class="help-strip">${tel?'Pilote le rituel et lis les cartes depuis ce téléphone.':'Prépare les maisons, puis relie ton téléphone pour lire les cartes habituelles.'} <button class="text-button" data-view="connection">${tel?'Changer de code':'Relier le téléphone'} →</button></div>`;}
  function students(){const snap=S.session&&!C.fin(S);return heading('Le choix des maisons','Bienvenue, les sorciers !','Les numéros correspondent aux cartes de la classe. Les maisons restent enregistrées d’une séance à l’autre.')+
      `<div class="toolbar"><button class="action secondary" data-act="import-open">Importer une sauvegarde</button>${button('local-import','Copier la classe du Bateau-école',true)}${button('split','Répartir les élèves sans maison',true)}</div>${snap?'<p class="info">La séance en cours garde sa répartition de départ. Ces changements s’appliqueront au prochain rituel.</p>':''}
      <div class="roster">${S.eleves.filter(e=>e.actif).map(e=>`<div class="student"><span class="card-number">${e.n}</span><b>${E(e.prenom||'Carte '+e.n)}</b><select data-house="${e.n}" aria-label="Maison de ${E(e.prenom||'la carte '+e.n)}" data-write><option value="">Choisir une maison</option>${H.map((h,i)=>`<option value="${i}" ${e.maison===i?'selected':''}>${h.nom}</option>`).join('')}</select><label class="presence"><input type="checkbox" data-absent="${e.n}" ${C.presents(S).some(x=>x.n===e.n)?'checked':''} data-write> Présent</label></div>`).join('')||'<p>Ta classe apparaîtra ici après un import ou une saisie ci-dessous.</p>'}</div>
      <details class="panel" ${S.eleves.length?'':'open'}><summary>Ajouter ou modifier les élèves</summary><p>Une ligne par carte : <b>1; Prénom</b>. Les cartes déjà présentes sont mises à jour. Une ligne retirée de cette zone conserve l’élève existant.</p><form id="roster-form"><label>Nom de la classe<input name="nom" value="${E(S.nom)}" maxlength="60"></label><label>Cartes et prénoms<textarea name="eleves" rows="8" placeholder="1; Prénom\n2; Prénom">${E(S.eleves.map(e=>e.n+'; '+e.prenom).join('\n'))}</textarea></label><button class="action" data-write>Enregistrer la liste</button></form></details>`;}
  function questions(){const bank=C.banque(S,B.questions);return heading('Préparer le rituel','Dans vos grimoires…',`${bank.length} questions disponibles. Le rituel en tire jusqu’à six au hasard, parmi les chapitres cochés.`)+`<p class="info">Les questions et les cartes sont celles du Bateau-école. Une sauvegarde importée reprend aussi tes questions adaptées et les chapitres déjà activés.</p><div class="notions">${B.notions.map(n=>`<label class="notion"><input type="checkbox" data-notion="${E(n.id)}" ${S.notions===null||S.notions.includes(n.id)?'checked':''} data-write><span><small>${E(B.matieres[n.m]?.nom||n.m)} · ${E(n.s||'')}</small><b>${E(n.t)}</b></span><span>${C.banque({...S,notions:[n.id]},B.questions).length}</span></label>`).join('')}</div><details class="panel"><summary>Parcourir les questions sélectionnées</summary>${bank.map(q=>`<div class="bank-question"><b>${E(q.q)}</b><p>${q.c.map((c,i)=>`${'ABCD'[i]}. ${E(c)}${i===q.ok?' ✓':''}`).join(' · ')}</p></div>`).join('')}</details>`;}
  function quiz(){const t=S.session;if(!t)return heading('Le rituel','Prépare les maisons pour commencer.')+button('start','Commencer');const q=t.questions[t.index],revealed=t.index<t.valide,rep=t.reponses[t.index],count=t.roster.filter(e=>rep[e.n]).length;
    if(tel)return `<section class="phone-ritual"><div class="quiz-top"><span class="eyebrow">Le rituel · ${t.index+1} / ${t.questions.length}</span><b>${count} / ${t.roster.length} réponses</b></div><h1>${E(q.q)}</h1><details class="phone-options" ${revealed?'open':''}><summary>${revealed?'La bonne réponse : '+ 'ABCD'[q.ok]:'Afficher les choix'}</summary><div class="answers">${q.c.map((c,i)=>`<div class="answer ${revealed&&i===q.ok?'correct':''}"><span>${'ABCD'[i]}</span><b>${E(c)}</b></div>`).join('')}</div>${revealed?`<p>${E(q.exp||q.c[q.ok])}</p>`:''}</details><div class="phone-actions">${!revealed?button('reveal','Voir la réponse',false,`data-qid="${E(C.qid(S))}"`):C.fin(S)?button('podium','Découvrir le podium'):button('next','Question suivante →',false,`data-qid="${E(C.qid(S))}"`)}</div><details class="manual-answers"><summary>Vérifier ou corriger les réponses</summary><div class="responses">${t.roster.map(e=>`<label class="response"><span><b>${e.n}</b> ${E(e.prenom||'Carte '+e.n)}<small>${house(e.maison)}</small></span><select data-answer="${e.n}" aria-label="Réponse carte ${e.n}" ${revealed?'disabled':'data-write'}><option value="">—</option>${q.c.map((_,i)=>`<option ${rep[e.n]==='ABCD'[i]?'selected':''}>${'ABCD'[i]}</option>`).join('')}</select></label>`).join('')}</div></details></section>`;
    return `<div class="quiz-top"><span class="eyebrow">Le rituel des maisons</span><span>Question ${t.index+1} / ${t.questions.length}</span></div><div class="progress"><span style="width:${(t.index+1)/t.questions.length*100}%"></span></div><div class="quiz-layout ${tel?'phone':''}"><section class="question-panel"><div class="eyebrow">${E(B.notions.find(n=>n.id===q.n)?.t||'Le défi du jour')}</div><h1 class="question">${E(q.q)}</h1><div class="answers">${q.c.map((c,i)=>`<div class="answer ${revealed&&i===q.ok?'correct':''}"><span>${'ABCD'[i]}</span><b>${E(c)}</b>${revealed&&i===q.ok?'<strong aria-label="Bonne réponse">✓</strong>':''}</div>`).join('')}</div>${revealed?`<div class="explanation"><b>Le savoir à retenir</b><p>${E(q.exp||q.c[q.ok])}</p></div>`:`<p class="lift">Levez vos cartes ! <span>${count} / ${t.roster.length} réponses reçues</span></p>`}<div class="quiz-actions">${!revealed?button('reveal','Voir la réponse',false,`data-qid="${E(C.qid(S))}"`):C.fin(S)?button('podium','Découvrir le podium'):button('next','Question suivante →',false,`data-qid="${E(C.qid(S))}"`)}</div></section>
      <aside class="control"><h2>${tel?'Les cartes':'Lecture des cartes'}</h2><p>${tel?'Lis les cartes avec la caméra. Tu peux corriger une réponse à la main.':'Relie le téléphone pour lire les cartes. Tu peux aussi saisir les réponses ici.'}</p><div class="counter"><strong>${count}</strong><span>sur ${t.roster.length} réponses</span></div><details ${tel?'open':''}><summary>${tel?'Réponses des élèves':'Saisie manuelle'}</summary><div class="responses">${t.roster.map(e=>`<label class="response"><span><b>${e.n}</b> ${tel?E(e.prenom):'Carte '+e.n}<small>${house(e.maison)}</small></span><select data-answer="${e.n}" aria-label="Réponse carte ${e.n}" ${revealed?'disabled':'data-write'}><option value="">—</option>${q.c.map((_,i)=>`<option ${rep[e.n]==='ABCD'[i]?'selected':''}>${'ABCD'[i]}</option>`).join('')}</select></label>`).join('')}</div></details></aside></div>${houses(C.scores(t))}`;}
  function podium(){const scores=podiumTotal?C.total(S):C.scores(S.session),ranks=C.rangs(scores),complete=C.fin(S),equal=ranks.filter(r=>r.points===ranks[0].points).length;
    return `<div class="podium-title"><div class="eyebrow">La coupe des quatre maisons</div><h1>${complete?'Bravo, les sorciers !':'À vous de jouer, les maisons !'}</h1><p>${podiumTotal?'Les points de tous les rituels de cet essai.':complete?'Bravo à toute la classe ! Voici les points du rituel.':'Le classement se construit au fil des réponses validées.'}</p><div class="switch"><button data-scores="session" aria-pressed="${!podiumTotal}">Ce rituel</button><button data-scores="total" aria-pressed="${podiumTotal}">Depuis le début</button></div></div><div class="podium">${ranks.map((r,i)=>`<article class="podium-item" style="--house:${H[r.h].couleur};--height:${70+(4-r.rang)*35}px;--order:${[1,0,2,3][i]};--rank:${r.rang}">${crest(r.h)}<h2>${house(r.h)}</h2><strong>${r.points}<small>points</small></strong><div class="podium-step"><b>${r.rang===1?'1re':r.rang+'e'} place</b>${ranks.filter(x=>x.points===r.points).length>1?'<span>ex æquo</span>':''}</div></article>`).join('')}</div><div class="help-strip">+5 points par bonne réponse · Les réponses non lues et les erreurs n’en retirent aucun.${equal===4?' Les quatre maisons sont à égalité.':''}</div><div class="center toolbar">${button('home','Retour au château',true)}${complete?'<button class="action" data-view="secret">Le secret de la serre →</button>':''}</div>`;}
  function secret(){return `<section class="secret"><img src="assets/serre.webp" alt="Un petit dragon de feuilles veille sur une graine lumineuse dans la serre."><div><div class="eyebrow">Le rendez-vous du vendredi · Chapitre d’essai</div><h1>${S.sceau?'La serre s’éveille.':'La serre oubliée'}</h1><p>${S.sceau?'La graine s’illumine. Dans un froissement de feuilles, un minuscule dragon ouvre les yeux… Le gardien de la serre vous confie le premier sceau du château.':'Derrière une porte couverte de lierre, une graine attend les savoirs des quatre maisons. Aucun classement ne ferme cette porte : toute la classe découvre le secret ensemble.'}</p>${S.sceau?'<div class="seal-earned">✧ Le sceau de la serre est retrouvé !</div>':C.fin(S)?button('seal','Tester l’ouverture du secret'): '<p class="info">Termine un rituel pour tester la découverte du vendredi.</p>'}<p class="muted">Pour cet essai, tu peux ouvrir le secret n’importe quel jour après un rituel complet.</p>${button('home','Revenir au château',true)}</div></section>`;}
  function connection(){const code=Autonome.Liaison.code();if(tel)return heading('La télécommande','Relier ce téléphone','Ouvre l’essai sur l’ordinateur et garde la page ouverte. Recopie le code affiché dans Téléphone.')+`<form id="join-form" class="panel narrow"><label>Code de l’écran<input name="code" placeholder="XXXXX-XXXXX" value="${E(code||'')}" autocomplete="off" autocapitalize="characters" maxlength="15" required></label><button class="action">Relier le téléphone</button><p>La caméra utilise les cartes habituelles du Bateau-école. Autorise la caméra dans ton navigateur lorsqu’il le demande.</p></form>`;
    const u=new URL(location.href);u.search='?role=tel';u.hash=code?'lien='+code:'';let qr='';try{if(code)qr=Autonome.Liaison.qr(code,240,u.href);}catch(e){}
    return heading('Lire les cartes','Le téléphone de la maîtresse','Scanne ce QR code avec l’appareil photo du téléphone, puis ouvre le lien dans Safari ou Chrome.')+`<div class="connection panel"><div class="qr">${qr||'Préparation du code…'}</div><div><div class="eyebrow">Code de l’écran</div><strong class="link-code">${E(code||'…')}</strong><p>Garde cette page ouverte sur l’ordinateur. Les deux appareils ont besoin d’internet.</p><a class="action secondary" href="${E(u.href)}" target="_blank" rel="noopener">Ouvrir la télécommande</a><p class="muted">Cette télécommande web sert uniquement à l’essai. Le code du Bateau-école reste indépendant.</p></div></div>`;}
  function backups(){return heading('Garder une copie','Les sauvegardes de l’essai','La progression est enregistrée dans ce navigateur. Télécharge une copie pour retrouver tes maisons et tes points sur un autre ordinateur.')+`<div class="panel narrow"><h2>${E(S.nom)}</h2><p>${S.eleves.length} élèves · ${S.historique.length+(C.fin(S)?1:0)} rituels terminés</p><div class="toolbar"><button class="action" data-act="export">Télécharger une copie</button><button class="action secondary" data-act="import-open">Importer un fichier</button></div><p>Un fichier Bateau-école copie la classe et ses questions dans cet essai. Une sauvegarde de cet essai restaure ses maisons, ses points et son historique.</p>${tel?'<p class="info">La restauration complète se fait sur l’ordinateur. Tu peux télécharger la copie reçue par ce téléphone.</p>':''}</div>${incomingFile?`<div class="panel confirm"><h2>Restaurer cette sauvegarde ?</h2><p>${E(incomingFile.nom)} · ${incomingFile.eleves.length} élèves. L’état actuel de l’essai sera remplacé. Une copie sera téléchargée avant la restauration.</p><button class="action" data-act="restore">Télécharger l’état actuel et restaurer</button><button class="action secondary" data-act="cancel-import">Annuler</button></div>`:''}`;}
  const views={home,students,questions,quiz,podium,secret,connection,backup:backups};
  function draw(){if(!$('.a-content'))return;const details=[...document.querySelectorAll('.a-content details[open]')].map(e=>e.className).filter(Boolean);$('.a-content').innerHTML=(views[view]||home)();details.forEach(c=>{const d=document.querySelector('details.'+c);if(d)d.open=true;});document.querySelectorAll('[data-view]').forEach(el=>el.setAttribute('aria-current',el.dataset.view===view?'page':'false'));status();
    const holder=$('#camera-holder'),show=tel&&view==='quiz'&&!!S.session;holder.hidden=!show;
    if(show&&window.CameraDirect){if(!cameraMounted){CameraDirect.monte(holder,{surCartes:cards=>{if(!connected()||view!=='quiz'||S.session.index!==S.session.valide)return;const qid=C.qid(S);if(scanPending.qid!==qid)scanPending={qid,reponses:{}};Object.assign(scanPending.reponses,cards);if(!scanTimer)scanTimer=setTimeout(()=>{scanTimer=null;if(scanPending.qid===C.qid(S)&&connected())room.emit('scan',{app:'sorciers-v1',owner:S.id,...scanPending});},180);}});cameraMounted=true;}
      const qid=C.qid(S);CameraDirect.question(S.session.index===S.session.valide,qid!==lastQ);lastQ=qid;
    }else if(cameraMounted){CameraDirect.coupe();lastQ=null;}
    if($('#music'))$('#music').volume=Number($('#music-volume').value)/100*(view==='quiz'?.35:1);
  }
  function readLocal(){let k=null;try{const raw=localStorage.getItem('bateau-db:classe/actuelle');if(raw)k=JSON.parse(raw)?.data;}catch(e){}if(!k?.eleves){notice('Aucune classe Bateau-école trouvée dans ce navigateur. Importe sa sauvegarde JSON, ou saisis les élèves.',true);return;}send('import',{data:{classe:k}});}
  function parseRoster(form){const lines=form.eleves.value.split(/\r?\n/).filter(s=>s.trim()),map=new Map(S.eleves.map(e=>[e.n,e]));for(const line of lines){const m=/^\s*(\d{1,2})\s*[;,:\t]\s*(.+?)\s*$/.exec(line);if(!m)throw Error('Utilise une ligne « numéro; prénom » pour chaque carte.');const n=+m[1];map.set(n,C.eleve({...map.get(n),n,prenom:m[2],actif:true}));}const nums=lines.map(l=>+l.match(/^\s*\d+/)[0]);if(new Set(nums).size!==nums.length)throw Error('Un numéro apparaît deux fois dans la liste.');return {eleves:C.listeEleves([...map.values()]),nom:form.nom.value};}
  function events(){
    document.addEventListener('click',async ev=>{const el=ev.target.closest('button[data-act],button[data-view],button[data-scores]');if(!el||el.disabled)return;
      if(el.dataset.view){setView(el.dataset.view);return;}if(el.dataset.scores){podiumTotal=el.dataset.scores==='total';draw();return;}
      const act=el.dataset.act;notice('');
      if(act==='export')return backup();if(act==='import-open')return $('#import-file').click();if(act==='local-import')return readLocal();
      if(act==='cancel-import'){incomingFile=null;draw();return;}
      if(act==='restore'){if(tel||!incomingFile)return;backup();const oldRev=S.rev;S=incomingFile;S.id=C.uid();S.rev=oldRev+1;incomingFile=null;corrupt=false;shared='home';view='students';save();draw();broadcast();return;}
      send(act,{qid:el.dataset.qid||C.qid(S)});
    });
    document.addEventListener('change',ev=>{const el=ev.target;if(el.dataset.house!==undefined)send('house',{n:+el.dataset.house,h:el.value===''?null:+el.value});else if(el.dataset.absent)send('absent',{n:+el.dataset.absent,absent:!el.checked});else if(el.dataset.answer)send('answer',{qid:C.qid(S),reponses:{[el.dataset.answer]:el.value||null}});else if(el.dataset.notion)send('notion',{id:el.dataset.notion,enabled:el.checked});});
    document.addEventListener('submit',async ev=>{if(!['roster-form','join-form'].includes(ev.target.id))return;ev.preventDefault();try{if(ev.target.id==='roster-form'){send('roster',parseRoster(ev.target.elements));}else{const c=Autonome.Liaison.normalise(ev.target.elements.code.value);if(!c)throw Error('Le code doit contenir 10 lettres ou chiffres.');await Autonome.Liaison.fixe(c);location.hash='';location.reload();}}catch(e){notice(e.message,true);}});
    $('#import-file').addEventListener('change',async ev=>{const f=ev.target.files[0];ev.target.value='';if(!f)return;try{if(f.size>8*1024*1024)throw Error('Ce fichier est trop volumineux (maximum 8 Mo).');const data=JSON.parse(await f.text());if(data.format==='sorciers-essai/sauvegarde'){if(tel)throw Error('Restaure ce fichier sur l’ordinateur.');incomingFile=C.restore(data);view='backup';draw();}else{const check=C.clone(S);C.importer(check,data);send('import',{data});}}catch(e){notice('Import impossible : '+e.message,true);}});
    $('#music-toggle').addEventListener('click',async()=>{const a=$('#music');try{if(a.paused)await a.play();else a.pause();$('#music-toggle').setAttribute('aria-pressed',String(!a.paused));$('#music-toggle').textContent=a.paused?'♫ Musique':'Ⅱ Couper la musique';}catch(e){notice('La musique n’a pas pu démarrer. Réessaie après le chargement.',true);}});
    $('#music-volume').addEventListener('input',()=>{$('#music').volume=Number($('#music-volume').value)/100*(view==='quiz'?.35:1);});
    addEventListener('storage',e=>{if(!tel&&e.key===KEY&&e.newValue){try{const n=C.restore(JSON.parse(e.newValue));if(n.id!==S.id||n.rev>S.rev){S=n;draw();broadcast();}}catch(e){}}});
  }
  function boot(){document.body.classList.toggle('phone-mode',tel);try{const raw=localStorage.getItem(tel?MIRROR:KEY);if(raw)S=C.restore(JSON.parse(raw));}catch(e){corrupt=!tel;notice('La sauvegarde locale ne peut pas être lue. Elle est conservée. Tu peux restaurer une copie dans Sauvegarde.',true);}view=tel?'connection':S.session?(C.fin(S)?'podium':'quiz'):'home';shared=view;events();draw();connect();
    setInterval(()=>{status();if(!tel)broadcast();for(const [id,p] of pending){if(Date.now()-p.cmd.at>16000){pending.delete(id);notice('La commande n’a pas été confirmée par l’écran. Vérifie la connexion avant de réessayer.',true);}else if(connected()&&p.tries++<5)room.emit('cmd',p.cmd);}},2500);
  }
  return {boot};
})();
